import os

dirs = [
    os.path.join('data', 'raw'), # The path, data refers to base directory and raw refers to child directory
    os.path.join('data','processed'), # The data path of the Converted data aka pre porcessed data
    # os.path.join is mainly used in order to join the two differenent file paths with ease, for one single file folder no need of os.path.join
    'notebooks', # The path of the code where the models are created
    'saved_models', # The models generated by the code
    'src' # All the datasets are stored
]

for dir_ in dirs:
    os.makedirs(dir_, exist_ok=True)
    with open(os.path.join(dir_, ".gitkeep"), 'w') as f:
        pass

files = [
    'dvc.yaml',
    'params.yaml',
    '.gitignore',
    os.path.join('src','__init__.py'),   
]

for file_ in files:
    with open(file_, 'w') as f:
        pass